---
title: "Visuals"
author: "Chang Yu"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Visualizations
```{r}
glmer2 = glmer(happy~country + (1|country),
               data=train,
               nAGQ=0, # This argument is necessary for convergence
               family='binomial')

anova(glmer2, glmer1)
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(relationship) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = relationship,
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Relationship Category',
       y = 'Mean Happiness', 
       title = 'Happiness by Relationship Category',
       subtitle = 'A higher score corresponds to higher happiness')
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(occupation) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = occupation,
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Occupation Category',
       y = 'Mean Happiness', 
       title = 'Happiness by Occupation Category',
       subtitle = 'A higher score corresponds to higher happiness')
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(income) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = reorder(income, mean_happiness),
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Income Bracket (Increasing from Left to Right)',
       y = 'Mean Happiness', 
       title = 'Happiness by Income Bracket',
       subtitle = 'A higher score corresponds to higher happiness')
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(healthy) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = reorder(healthy, mean_happiness),
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Healthy',
       y = 'Mean Happiness', 
       title = 'Happiness by Health',
       subtitle = 'A higher score corresponds to higher happiness')
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(religious) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = reorder(religious, mean_happiness),
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Religious',
       y = 'Mean Happiness', 
       title = 'Happiness by Religious Indicator',
       subtitle = 'A higher score corresponds to higher happiness')
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(urban) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = reorder(urban, mean_happiness),
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Urban Indicator',
       y = 'Mean Happiness', 
       title = 'Happiness by Urban Indicator',
       subtitle = 'A higher score corresponds to higher happiness')
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(education) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = reorder(education, mean_happiness),
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Education',
       y = 'Mean Happiness', 
       title = 'Happiness by Education Category',
       subtitle = 'A higher score corresponds to higher happiness')
```

```{r}
train  %>% 
  mutate(happy_full = happy_full_train) %>%
  group_by(religion) %>% 
  summarize(mean_happiness = mean(as.numeric(happy)-1)) %>% 
  ggplot(aes(x = religion,
             y = mean_happiness,
             width = 0.8)) + 
  geom_bar(stat = 'identity') + 
  ylim(0, 1) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x = 'Religion',
       y = 'Mean Happiness', 
       title = 'Happiness by Religion',
       subtitle = 'A higher score corresponds to higher happiness')
```

