---
title: "Data Wrangling"
author: "Dasha Metropolitansky"
date: "11/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading packages
library(tidyverse)
library(janitor)
library(countrycode)

# Reading in the data
load('WVS_Cross-National_Wave_7_R_v1_4.rdata') 
df_full = `WVS_Cross-National_Wave_7_R_v1_4` %>% 
  clean_names()
rm(`WVS_Cross-National_Wave_7_R_v1_4`)
```

# Filtering for observations from the 7th wave of the World Values Survey
```{r}
df_full = df_full %>% 
  filter(a_study == 2 & a_wave == 7)
```

# Selecting variables
```{r}
# Selecting relevant variables
df_filtered = df_full %>% 
  select(a_year, b_country_alpha, g_townsize2, h_settlement, h_urbrural,
         q46, q47,
         q94, q95, q96, q97, q98, q99, q100, q101, q102, q103, q104,
         q173,
         q209, q210, q211, q212, q221, q222,
         q240, 
         q260, q262, q263, q264, q265, q269, q270, q271, q273, q274, 
         q275r, q277r, q278r, q279, q281, q284, q285, q288r, q289)

# Changing variable names
colnames(df_filtered) = c('year', 'country', 'town_size', 'settlement_type', 'urban',
                 'happy', 'healthy',
                 'church_member', 'sport_member', 'arts_member', 'union_member', 'political_party_member',
                 'environment_member', 'prof_member', 'charity_member', 'consumer_member', 'self_help_member',
                 'women_member', 
                 'religious', 
                 'political_1', 'political_2', 'political_3', 'political_4', 'political_5', 'political_6',
                 'ideology',
                 'gender', 'age', 'immigrant', 'immigrant_mother', 'immigrant_father', 'citizen', 'household_size',
                 'live_with_parents', 'relationship', 'num_kids', 'education', 'education_mother',
                 'education_father','employment_status', 'occupation', 'sector', 'breadwinner', 'income', 'religion')
```

# Modifying variables
```{r}
df = df_filtered %>%
  # Converting urban into an indicator variable
  mutate(urban = case_when(urban == 1 ~ 1,
                           urban == 2 ~ 2,
                           TRUE ~ NA_real_),
  # Converting happy into an indicator variable
         happy = case_when(happy == 1 | happy == 2 ~ 1,
                           happy == 3 | happy == 4 ~ 0,
                           TRUE ~ NA_real_),
  # Converting health into an indicator variable
         healthy = case_when(healthy %in% c(1,2,3) ~ 1,
                             healthy %in% c(4,5) ~ 0,
                             TRUE ~ NA_real_)) %>% 
  # Converting the membership variables into indicator variables
  mutate_at(
    vars(one_of('church_member', 'sport_member', 'arts_member', 'union_member', 'political_party_member',
                 'environment_member', 'prof_member', 'charity_member', 'consumer_member', 'self_help_member',
                 'women_member')),
    list(~case_when(
      . == 2 ~ 1,
      . == 1 | . == 0 ~ 0,
      TRUE ~ NA_real_))) %>%
  # Converting religious into an indicator variable
  mutate(religious = case_when(religious == 1 ~ 1,
                               religious == 2 | religious == 3 ~ 0,
                               TRUE ~ NA_real_)) %>%
  # Assigning responses to the political variables a score 
  mutate_at(
    vars(one_of('political_1', 'political_2', 'political_3', 'political_4', 'political_5', 'political_6')),
    list(~case_when(
      . == 1 ~ 2,
      . == 2 ~ 1,
      . == 3 ~ 0,
      TRUE ~ NA_real_))) %>% 
  # Creating one political variable which is the sum of political variables' scores 
  mutate(political = rowSums(select(., political_1:political_4))) %>% 
  select(-c(political_1:political_6)) %>% 
  # Converting gender into an indicator variables
  mutate(male = case_when(gender == 1 ~ 1,
                          gender == 2 ~ 0,
                          TRUE ~ NA_real_)) %>% 
  select(-c(gender)) %>%
  # Converting immigration variables into indicator variables
  mutate_at(
    vars(one_of('immigrant', 'immigrant_mother', 'immigrant_father')),
    list(~case_when(
      . == 2 ~ 1,
      . == 1 | . == 0 ~ 0,
      TRUE ~ NA_real_))) %>% 
  # Converting citizen into an indicator variable
  mutate(citizen = case_when(citizen == 1 ~ 1,
                             citizen == 2 | citizen == 3 ~ 0,
                             TRUE ~ NA_real_),
  # Converting live_with_parents into an indicator variable
         live_with_parents = case_when(live_with_parents == 1 ~ 0,
                             live_with_parents %in% c(2,3,4) ~ 1,
                             TRUE ~ NA_real_),
  # Converting relationship into an indicator variable
         relationship = case_when(relationship == 1 | relationship == 2 ~ 1,
                                  relationship %in% c(3,4,5,6) ~ 0,
                             TRUE ~ NA_real_),
  # Converting breadwinner into an indicator variable
         breadwinner = case_when(breadwinner == 1 ~ 1,
                                 breadwinner == 2 ~ 0)) %>%
  # Replacing all entries which are negative numbers with NA
  mutate_each(funs(replace(., .<0, NA))) %>% 
  # Converting relevant variables to factors
  mutate_at(
    vars(one_of('country', 'town_size', 'settlement_type', 'urban', 'happy', 'healthy',
                'church_member', 'sport_member', 'arts_member', 'union_member', 'political_party_member',
                 'environment_member', 'prof_member', 'charity_member', 'consumer_member', 'self_help_member',
                 'women_member', 'religious', 'male', 'immigrant', 'immigrant_mother', 'immigrant_father',
                'citizen', 'live_with_parents', 'relationship', 'education', 'education_mother', 'education_father',
                'employment_status', 'occupation', 'sector', 'breadwinner', 'income', 'religion')),
    list(~as.factor(.)))

# Removing unnecessary data frames
rm(df_full, df_filtered)
```

